var searchData=
[
  ['newtonsolver_0',['newtonsolver',['../structmfem__mgis_1_1_newton_solver.html#a9cea657c14d5b7b30e2753f03ec6f2ea',1,'mfem_mgis::NewtonSolver::NewtonSolver(NonLinearEvolutionProblemImplementation&lt; false &gt; &amp;p)'],['../structmfem__mgis_1_1_newton_solver.html#a330c7eb16bf14a134f6017789d127b39',1,'mfem_mgis::NewtonSolver::NewtonSolver(NonLinearEvolutionProblemImplementation&lt; true &gt; &amp;p)']]],
  ['nonlinearevolutionproblem_1',['nonlinearevolutionproblem',['../structmfem__mgis_1_1_non_linear_evolution_problem.html#a6d0963dad6d93f55f1642d7039674747',1,'mfem_mgis::NonLinearEvolutionProblem::NonLinearEvolutionProblem(Context &amp;ctx, const Parameters &amp;p)'],['../structmfem__mgis_1_1_non_linear_evolution_problem.html#ab744ab53f1520840f6ba54871d5d42fc',1,'mfem_mgis::NonLinearEvolutionProblem::NonLinearEvolutionProblem(Context &amp;ctx, MeshDiscretization &amp;m, const Parameters &amp;p)'],['../structmfem__mgis_1_1_non_linear_evolution_problem.html#a9f5bf0aec51c1900fae85715f1b3f774',1,'mfem_mgis::NonLinearEvolutionProblem::NonLinearEvolutionProblem(Context &amp;ctx, MeshDiscretization &amp;m, const Hypothesis h, const Parameters &amp;p=Parameters())'],['../structmfem__mgis_1_1_non_linear_evolution_problem.html#a4912f618f14f8889846cda9f72fbd631',1,'mfem_mgis::NonLinearEvolutionProblem::NonLinearEvolutionProblem(Context &amp;ctx, std::shared_ptr&lt; FiniteElementDiscretization &gt; fed, const Parameters &amp;p)'],['../structmfem__mgis_1_1_non_linear_evolution_problem.html#a26f5060bd0600be5f3700192dbbbf7dc',1,'mfem_mgis::NonLinearEvolutionProblem::NonLinearEvolutionProblem(Context &amp;ctx, std::shared_ptr&lt; FiniteElementDiscretization &gt; fed, const Hypothesis h, const Parameters &amp;p=Parameters())'],['../structmfem__mgis_1_1_non_linear_evolution_problem.html#aa4cc29d04d69be4c5f5fa9bf7f51e131',1,'mfem_mgis::NonLinearEvolutionProblem::NonLinearEvolutionProblem(NonLinearEvolutionProblem &amp;&amp;) noexcept=default'],['../structmfem__mgis_1_1_non_linear_evolution_problem.html#ae35797613998c326a23e850802c1310a',1,'mfem_mgis::NonLinearEvolutionProblem::NonLinearEvolutionProblem(const NonLinearEvolutionProblem &amp;) noexcept=delete']]],
  ['nonlinearevolutionproblemimplementation_2',['nonlinearevolutionproblemimplementation',['../structmfem__mgis_1_1_non_linear_evolution_problem_implementation_3_01true_01_4.html#aba13a2e62dc0ec35da115d343e5c37ea',1,'mfem_mgis::NonLinearEvolutionProblemImplementation&lt; true &gt;::NonLinearEvolutionProblemImplementation()'],['../structmfem__mgis_1_1_non_linear_evolution_problem_implementation_3_01false_01_4.html#a3fb07d7f73cd72b43e19a76e48aeab59',1,'mfem_mgis::NonLinearEvolutionProblemImplementation&lt; false &gt;::NonLinearEvolutionProblemImplementation()']]],
  ['nonlinearevolutionproblemimplementationbase_3',['NonLinearEvolutionProblemImplementationBase',['../structmfem__mgis_1_1_non_linear_evolution_problem_implementation_base.html#a86612bbd0ce8f7ce3c4ffc4d955926f1',1,'mfem_mgis::NonLinearEvolutionProblemImplementationBase']]],
  ['nonlinearmodel_4',['nonlinearmodel',['../structmfem__mgis_1_1_non_linear_model.html#a6416e190bfa394f5db61b55122e99caf',1,'mfem_mgis::NonLinearModel::NonLinearModel(Context &amp;ctx, MeshDiscretization &amp;m, const Parameters &amp;parameters)'],['../structmfem__mgis_1_1_non_linear_model.html#a6f55db09fd228e078e1fc819a71d594a',1,'mfem_mgis::NonLinearModel::NonLinearModel(Context &amp;ctx, std::shared_ptr&lt; NonLinearEvolutionProblem &gt; p)']]],
  ['nonlinearsolverbase_5',['nonlinearsolverbase',['../structmfem__mgis_1_1_non_linear_solver_base.html#a6c80ac31607966001bf164e29fb13902',1,'mfem_mgis::NonLinearSolverBase::NonLinearSolverBase(NonLinearEvolutionProblemImplementation&lt; true &gt; &amp;p)'],['../structmfem__mgis_1_1_non_linear_solver_base.html#a73435910fd78aad07ac79ed1b8f02790',1,'mfem_mgis::NonLinearSolverBase::NonLinearSolverBase(NonLinearEvolutionProblemImplementation&lt; false &gt; &amp;p)']]],
  ['nonlinearsolverfactory_6',['nonlinearsolverfactory',['../structmfem__mgis_1_1_non_linear_solver_factory.html#a79c6cec7a64f438f82cd2211c3bfb86f',1,'mfem_mgis::NonLinearSolverFactory::NonLinearSolverFactory(NonLinearSolverFactory &amp;&amp;)=delete'],['../structmfem__mgis_1_1_non_linear_solver_factory.html#abbb98ba98272a4347f58959478ce224d',1,'mfem_mgis::NonLinearSolverFactory::NonLinearSolverFactory(const NonLinearSolverFactory &amp;)=delete']]]
];
