var annotated_dup =
[
    [ "mfem_mgis", "namespacemfem__mgis.html", [
      [ "unit_tests", null, [
        [ "TestParameters", "structmfem__mgis_1_1unit__tests_1_1_test_parameters.html", null ],
        [ "UniaxialTestResults", "structmfem__mgis_1_1unit__tests_1_1_uniaxial_test_results.html", "structmfem__mgis_1_1unit__tests_1_1_uniaxial_test_results" ]
      ] ],
      [ "AbstractBehaviourIntegrator", "structmfem__mgis_1_1_abstract_behaviour_integrator.html", "structmfem__mgis_1_1_abstract_behaviour_integrator" ],
      [ "AbstractBoundaryCondition", "structmfem__mgis_1_1_abstract_boundary_condition.html", "structmfem__mgis_1_1_abstract_boundary_condition" ],
      [ "AbstractConvergenceFailureHandler", "structmfem__mgis_1_1_abstract_convergence_failure_handler.html", "structmfem__mgis_1_1_abstract_convergence_failure_handler" ],
      [ "AbstractCouplingItem", "structmfem__mgis_1_1_abstract_coupling_item.html", "structmfem__mgis_1_1_abstract_coupling_item" ],
      [ "AbstractCouplingScheme", "structmfem__mgis_1_1_abstract_coupling_scheme.html", "structmfem__mgis_1_1_abstract_coupling_scheme" ],
      [ "AbstractCouplingSchemeConvergenceCriterion", "structmfem__mgis_1_1_abstract_coupling_scheme_convergence_criterion.html", "structmfem__mgis_1_1_abstract_coupling_scheme_convergence_criterion" ],
      [ "AbstractCurve", "structmfem__mgis_1_1_abstract_curve.html", "structmfem__mgis_1_1_abstract_curve" ],
      [ "AbstractDirichletBoundaryCondition", "structmfem__mgis_1_1_abstract_dirichlet_boundary_condition.html", "structmfem__mgis_1_1_abstract_dirichlet_boundary_condition" ],
      [ "AbstractModel", "structmfem__mgis_1_1_abstract_model.html", "structmfem__mgis_1_1_abstract_model" ],
      [ "AbstractNonLinearEvolutionProblem", "structmfem__mgis_1_1_abstract_non_linear_evolution_problem.html", "structmfem__mgis_1_1_abstract_non_linear_evolution_problem" ],
      [ "AbstractNonLinearEvolutionProblemPostProcessing", "structmfem__mgis_1_1_abstract_non_linear_evolution_problem_post_processing.html", null ],
      [ "AbstractNonLinearEvolutionProblemPostProcessing< false >", "structmfem__mgis_1_1_abstract_non_linear_evolution_problem_post_processing_3_01false_01_4.html", "structmfem__mgis_1_1_abstract_non_linear_evolution_problem_post_processing_3_01false_01_4" ],
      [ "AbstractNonLinearEvolutionProblemPostProcessing< true >", "structmfem__mgis_1_1_abstract_non_linear_evolution_problem_post_processing_3_01true_01_4.html", "structmfem__mgis_1_1_abstract_non_linear_evolution_problem_post_processing_3_01true_01_4" ],
      [ "AbstractNonLinearSolver", "structmfem__mgis_1_1_abstract_non_linear_solver.html", "structmfem__mgis_1_1_abstract_non_linear_solver" ],
      [ "AbstractNonLinearSolverGenerator", "structmfem__mgis_1_1_abstract_non_linear_solver_generator.html", "structmfem__mgis_1_1_abstract_non_linear_solver_generator" ],
      [ "AbstractPostProcessing", "structmfem__mgis_1_1_abstract_post_processing.html", "structmfem__mgis_1_1_abstract_post_processing" ],
      [ "AbstractQPEvaluator", "structmfem__mgis_1_1_abstract_q_p_evaluator.html", "structmfem__mgis_1_1_abstract_q_p_evaluator" ],
      [ "AbstractQPEvaluatorGenerator", "structmfem__mgis_1_1_abstract_q_p_evaluator_generator.html", "structmfem__mgis_1_1_abstract_q_p_evaluator_generator" ],
      [ "AbstractSimulationMonitor", "structmfem__mgis_1_1_abstract_simulation_monitor.html", "structmfem__mgis_1_1_abstract_simulation_monitor" ],
      [ "AbstractTimeIncrementComputer", "structmfem__mgis_1_1_abstract_time_increment_computer.html", "structmfem__mgis_1_1_abstract_time_increment_computer" ],
      [ "AbstractTimeStepValidator", "structmfem__mgis_1_1_abstract_time_step_validator.html", "structmfem__mgis_1_1_abstract_time_step_validator" ],
      [ "BehaviourIntegratorBase", "structmfem__mgis_1_1_behaviour_integrator_base.html", "structmfem__mgis_1_1_behaviour_integrator_base" ],
      [ "BehaviourIntegratorFactory", "structmfem__mgis_1_1_behaviour_integrator_factory.html", "structmfem__mgis_1_1_behaviour_integrator_factory" ],
      [ "BehaviourIntegratorTraits", "structmfem__mgis_1_1_behaviour_integrator_traits.html", null ],
      [ "BehaviourIntegratorTraits< FBarIsotropicPlaneStrainBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_f_bar_isotropic_plane_strain_behaviour_integrator_01_4.html", null ],
      [ "BehaviourIntegratorTraits< FBarIsotropicTridimensionalBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_f_bar_isotropic_tridimensional_behaviour_integrator_01_4.html", null ],
      [ "BehaviourIntegratorTraits< FBarOrthotropicPlaneStrainBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_f_bar_orthotropic_plane_strain_behaviour_integrator_01_4.html", null ],
      [ "BehaviourIntegratorTraits< FBarOrthotropicTridimensionalBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_f_bar_orthotropic_tridimensional_behaviour_integrator_01_4.html", null ],
      [ "BehaviourIntegratorTraits< IsotropicPlaneStrainStandardFiniteStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_isotropic_plane_strain_standard_finite_str058555a310f31d3525091c27fe446de1.html", null ],
      [ "BehaviourIntegratorTraits< IsotropicPlaneStrainStandardSmallStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_isotropic_plane_strain_standard_small_strab03ca29ba6e154ecb055438675cf8841.html", null ],
      [ "BehaviourIntegratorTraits< IsotropicPlaneStrainStationaryNonLinearHeatTransferBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_isotropic_plane_strain_stationary_non_line763eaaeb4027aae18449d8f97a056eb1.html", null ],
      [ "BehaviourIntegratorTraits< IsotropicPlaneStressStandardFiniteStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_isotropic_plane_stress_standard_finite_strbd77ccca9ddae255fd5ac1ee873636a5.html", null ],
      [ "BehaviourIntegratorTraits< IsotropicPlaneStressStandardSmallStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_isotropic_plane_stress_standard_small_stra139874cef464eaafb1689d10b1e39543.html", null ],
      [ "BehaviourIntegratorTraits< IsotropicPlaneStressStationaryNonLinearHeatTransferBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_isotropic_plane_stress_stationary_non_line680d4dfc3d3114ba6c5360047e7abadd.html", null ],
      [ "BehaviourIntegratorTraits< IsotropicTridimensionalStandardFiniteStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_isotropic_tridimensional_standard_finite_s1234bc842a2a389342bd14f07fe4ec78.html", null ],
      [ "BehaviourIntegratorTraits< IsotropicTridimensionalStandardSmallStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_isotropic_tridimensional_standard_small_stb525bfbc70970b6cc9f76ee6026e5cb2.html", null ],
      [ "BehaviourIntegratorTraits< IsotropicTridimensionalStationaryNonLinearHeatTransferBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_isotropic_tridimensional_stationary_non_lie14e5cb5dd488b8c265cfe42f20567ec.html", null ],
      [ "BehaviourIntegratorTraits< OrthotropicPlaneStrainStandardFiniteStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_orthotropic_plane_strain_standard_finite_sd7dacb62a0757798a293664924599d11.html", null ],
      [ "BehaviourIntegratorTraits< OrthotropicPlaneStrainStandardSmallStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_orthotropic_plane_strain_standard_small_st0f4aa67dc89ad340d5cde8c05f2ac658.html", null ],
      [ "BehaviourIntegratorTraits< OrthotropicPlaneStrainStationaryNonLinearHeatTransferBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_orthotropic_plane_strain_stationary_non_li21e9368022b199aa1db822f7372565a8.html", null ],
      [ "BehaviourIntegratorTraits< OrthotropicPlaneStressStandardFiniteStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_orthotropic_plane_stress_standard_finite_s237fb33c5765bbc5b84b15bd6a23998e.html", null ],
      [ "BehaviourIntegratorTraits< OrthotropicPlaneStressStandardSmallStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_orthotropic_plane_stress_standard_small_st362c3e1c839cf61f476c652ee949a08c.html", null ],
      [ "BehaviourIntegratorTraits< OrthotropicPlaneStressStationaryNonLinearHeatTransferBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_orthotropic_plane_stress_stationary_non_li305b39e3239fc561e5f9eb21b39001bc.html", null ],
      [ "BehaviourIntegratorTraits< OrthotropicTridimensionalStandardFiniteStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_orthotropic_tridimensional_standard_finite80fd5621ba12a0fe0b2f6bdebdd9e4c0.html", null ],
      [ "BehaviourIntegratorTraits< OrthotropicTridimensionalStandardSmallStrainMechanicsBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_orthotropic_tridimensional_standard_small_5a4f15b906d3c681863e254a22446e58.html", null ],
      [ "BehaviourIntegratorTraits< OrthotropicTridimensionalStationaryNonLinearHeatTransferBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_orthotropic_tridimensional_stationary_non_f3c5025a602c5357d2adce42482f7d73.html", null ],
      [ "BehaviourIntegratorTraits< TransientHeatTransferBehaviourIntegrator >", "structmfem__mgis_1_1_behaviour_integrator_traits_3_01_transient_heat_transfer_behaviour_integrator_01_4.html", null ],
      [ "BidimensionalMicromorphicDamageBehaviourIntegrator", "structmfem__mgis_1_1_bidimensional_micromorphic_damage_behaviour_integrator.html", "structmfem__mgis_1_1_bidimensional_micromorphic_damage_behaviour_integrator" ],
      [ "ComputeNextStateOutput", "structmfem__mgis_1_1_compute_next_state_output.html", "structmfem__mgis_1_1_compute_next_state_output" ],
      [ "ComputeResultantForceOnBoundary", "structmfem__mgis_1_1_compute_resultant_force_on_boundary.html", null ],
      [ "ComputeResultantForceOnBoundary< false >", "structmfem__mgis_1_1_compute_resultant_force_on_boundary_3_01false_01_4.html", "structmfem__mgis_1_1_compute_resultant_force_on_boundary_3_01false_01_4" ],
      [ "ComputeResultantForceOnBoundary< true >", "structmfem__mgis_1_1_compute_resultant_force_on_boundary_3_01true_01_4.html", "structmfem__mgis_1_1_compute_resultant_force_on_boundary_3_01true_01_4" ],
      [ "ComputeResultantForceOnBoundaryCommon", "structmfem__mgis_1_1_compute_resultant_force_on_boundary_common.html", "structmfem__mgis_1_1_compute_resultant_force_on_boundary_common" ],
      [ "ConvergenceFailureHandlerBase", "structmfem__mgis_1_1_convergence_failure_handler_base.html", "structmfem__mgis_1_1_convergence_failure_handler_base" ],
      [ "CouplingSchemeBase", "structmfem__mgis_1_1_coupling_scheme_base.html", "structmfem__mgis_1_1_coupling_scheme_base" ],
      [ "CouplingSchemeConvergenceCriterionBase", "structmfem__mgis_1_1_coupling_scheme_convergence_criterion_base.html", "structmfem__mgis_1_1_coupling_scheme_convergence_criterion_base" ],
      [ "CurvesPostProcessing", "structmfem__mgis_1_1_curves_post_processing.html", "structmfem__mgis_1_1_curves_post_processing" ],
      [ "CurvesWriter", "structmfem__mgis_1_1_curves_writer.html", "structmfem__mgis_1_1_curves_writer" ],
      [ "DefaultConvergenceFailureHandler", "structmfem__mgis_1_1_default_convergence_failure_handler.html", "structmfem__mgis_1_1_default_convergence_failure_handler" ],
      [ "DefaultTimeIncrementComputer", "structmfem__mgis_1_1_default_time_increment_computer.html", "structmfem__mgis_1_1_default_time_increment_computer" ],
      [ "DefaultTimeStepValidator", "structmfem__mgis_1_1_default_time_step_validator.html", "structmfem__mgis_1_1_default_time_step_validator" ],
      [ "DependenciesManager", "structmfem__mgis_1_1_dependencies_manager.html", "structmfem__mgis_1_1_dependencies_manager" ],
      [ "DependencyBase", "structmfem__mgis_1_1_dependency_base.html", "structmfem__mgis_1_1_dependency_base" ],
      [ "DirichletBoundaryConditionBase", "structmfem__mgis_1_1_dirichlet_boundary_condition_base.html", "structmfem__mgis_1_1_dirichlet_boundary_condition_base" ],
      [ "DissipatedEnergyPostProcessing", "structmfem__mgis_1_1_dissipated_energy_post_processing.html", "structmfem__mgis_1_1_dissipated_energy_post_processing" ],
      [ "EnergyPostProcessingBase", "structmfem__mgis_1_1_energy_post_processing_base.html", "structmfem__mgis_1_1_energy_post_processing_base" ],
      [ "ExitStatus", "structmfem__mgis_1_1_exit_status.html", "structmfem__mgis_1_1_exit_status" ],
      [ "Faltus2026RegularizedIsotropicBehaviourIntegrator", "structmfem__mgis_1_1_faltus2026_regularized_isotropic_behaviour_integrator.html", "structmfem__mgis_1_1_faltus2026_regularized_isotropic_behaviour_integrator" ],
      [ "Faltus2026RegularizedIsotropicBehaviourIntegratorBaseDispatch", "structmfem__mgis_1_1_faltus2026_regularized_isotropic_behaviour_integrator_base_dispatch.html", null ],
      [ "Faltus2026RegularizedIsotropicBehaviourIntegratorBaseDispatch< Hypothesis::PLANESTRAIN >", "structmfem__mgis_1_1_faltus2026_regularized_isotropic_behaviour_integrator_base_dispatch_3_01_hyaa26bf8bf73500ccbab0c0881c6776f0.html", null ],
      [ "Faltus2026RegularizedIsotropicBehaviourIntegratorBaseDispatch< Hypothesis::PLANESTRESS >", "structmfem__mgis_1_1_faltus2026_regularized_isotropic_behaviour_integrator_base_dispatch_3_01_hy84eb42220287bea87d37518f2e58db7e.html", null ],
      [ "Faltus2026RegularizedIsotropicBehaviourIntegratorBaseDispatch< Hypothesis::TRIDIMENSIONAL >", "structmfem__mgis_1_1_faltus2026_regularized_isotropic_behaviour_integrator_base_dispatch_3_01_hy585a1f6e00216ee05121fca4c0a3aaad.html", null ],
      [ "FBarBehaviourIntegratorCRTPBase", "structmfem__mgis_1_1_f_bar_behaviour_integrator_c_r_t_p_base.html", "structmfem__mgis_1_1_f_bar_behaviour_integrator_c_r_t_p_base" ],
      [ "FBarIsotropicPlaneStrainBehaviourIntegrator", "structmfem__mgis_1_1_f_bar_isotropic_plane_strain_behaviour_integrator.html", "structmfem__mgis_1_1_f_bar_isotropic_plane_strain_behaviour_integrator" ],
      [ "FBarIsotropicTridimensionalBehaviourIntegrator", "structmfem__mgis_1_1_f_bar_isotropic_tridimensional_behaviour_integrator.html", "structmfem__mgis_1_1_f_bar_isotropic_tridimensional_behaviour_integrator" ],
      [ "FBarOrthotropicPlaneStrainBehaviourIntegrator", "structmfem__mgis_1_1_f_bar_orthotropic_plane_strain_behaviour_integrator.html", "structmfem__mgis_1_1_f_bar_orthotropic_plane_strain_behaviour_integrator" ],
      [ "FBarOrthotropicTridimensionalBehaviourIntegrator", "structmfem__mgis_1_1_f_bar_orthotropic_tridimensional_behaviour_integrator.html", "structmfem__mgis_1_1_f_bar_orthotropic_tridimensional_behaviour_integrator" ],
      [ "FiniteElementDiscretization", "structmfem__mgis_1_1_finite_element_discretization.html", "structmfem__mgis_1_1_finite_element_discretization" ],
      [ "FiniteElementSpacesManager", "structmfem__mgis_1_1_finite_element_spaces_manager.html", "structmfem__mgis_1_1_finite_element_spaces_manager" ],
      [ "FirstIterationConvergenceCriterion", "structmfem__mgis_1_1_first_iteration_convergence_criterion.html", "structmfem__mgis_1_1_first_iteration_convergence_criterion" ],
      [ "GridFunctionInterpolator", "structmfem__mgis_1_1_grid_function_interpolator.html", "structmfem__mgis_1_1_grid_function_interpolator" ],
      [ "GridFunctionValuesCurve", "structmfem__mgis_1_1_grid_function_values_curve.html", "structmfem__mgis_1_1_grid_function_values_curve" ],
      [ "ImmutablePartialQuadratureFunctionView", "structmfem__mgis_1_1_immutable_partial_quadrature_function_view.html", "structmfem__mgis_1_1_immutable_partial_quadrature_function_view" ],
      [ "ImposedDirichletBoundaryConditionAtClosestNode", "structmfem__mgis_1_1_imposed_dirichlet_boundary_condition_at_closest_node.html", "structmfem__mgis_1_1_imposed_dirichlet_boundary_condition_at_closest_node" ],
      [ "IsotropicPlaneStrainStandardFiniteStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_isotropic_plane_strain_standard_finite_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_isotropic_plane_strain_standard_finite_strain_mechanics_behaviour_integrator" ],
      [ "IsotropicPlaneStrainStandardSmallStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_isotropic_plane_strain_standard_small_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_isotropic_plane_strain_standard_small_strain_mechanics_behaviour_integrator" ],
      [ "IsotropicPlaneStrainStationaryNonLinearHeatTransferBehaviourIntegrator", "structmfem__mgis_1_1_isotropic_plane_strain_stationary_non_linear_heat_transfer_behaviour_integrator.html", "structmfem__mgis_1_1_isotropic_plane_strain_stationary_non_linear_heat_transfer_behaviour_integrator" ],
      [ "IsotropicPlaneStressStandardFiniteStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_isotropic_plane_stress_standard_finite_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_isotropic_plane_stress_standard_finite_strain_mechanics_behaviour_integrator" ],
      [ "IsotropicPlaneStressStandardSmallStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_isotropic_plane_stress_standard_small_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_isotropic_plane_stress_standard_small_strain_mechanics_behaviour_integrator" ],
      [ "IsotropicPlaneStressStationaryNonLinearHeatTransferBehaviourIntegrator", "structmfem__mgis_1_1_isotropic_plane_stress_stationary_non_linear_heat_transfer_behaviour_integrator.html", "structmfem__mgis_1_1_isotropic_plane_stress_stationary_non_linear_heat_transfer_behaviour_integrator" ],
      [ "IsotropicTridimensionalStandardFiniteStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_isotropic_tridimensional_standard_finite_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_isotropic_tridimensional_standard_finite_strain_mechanics_behaviour_integrator" ],
      [ "IsotropicTridimensionalStandardSmallStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_isotropic_tridimensional_standard_small_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_isotropic_tridimensional_standard_small_strain_mechanics_behaviour_integrator" ],
      [ "IsotropicTridimensionalStationaryNonLinearHeatTransferBehaviourIntegrator", "structmfem__mgis_1_1_isotropic_tridimensional_stationary_non_linear_heat_transfer_behaviour_integrator.html", "structmfem__mgis_1_1_isotropic_tridimensional_stationary_non_linear_heat_transfer_behaviour_integrator" ],
      [ "IterativeCouplingScheme", "structmfem__mgis_1_1_iterative_coupling_scheme.html", "structmfem__mgis_1_1_iterative_coupling_scheme" ],
      [ "L2ProjectionResult", "structmfem__mgis_1_1_l2_projection_result.html", "structmfem__mgis_1_1_l2_projection_result" ],
      [ "LinearizedOperators", "structmfem__mgis_1_1_linearized_operators.html", "structmfem__mgis_1_1_linearized_operators" ],
      [ "LinearSolverFactory", "structmfem__mgis_1_1_linear_solver_factory.html", null ],
      [ "LinearSolverFactory< false >", "structmfem__mgis_1_1_linear_solver_factory_3_01false_01_4.html", "structmfem__mgis_1_1_linear_solver_factory_3_01false_01_4" ],
      [ "LinearSolverFactory< true >", "structmfem__mgis_1_1_linear_solver_factory_3_01true_01_4.html", "structmfem__mgis_1_1_linear_solver_factory_3_01true_01_4" ],
      [ "LinearSolverHandler", "structmfem__mgis_1_1_linear_solver_handler.html", null ],
      [ "LoopCouplingScheme", "structmfem__mgis_1_1_loop_coupling_scheme.html", "structmfem__mgis_1_1_loop_coupling_scheme" ],
      [ "Material", "structmfem__mgis_1_1_material.html", "structmfem__mgis_1_1_material" ],
      [ "MaterialQuantityProviderSearchResult", "structmfem__mgis_1_1_material_quantity_provider_search_result.html", "structmfem__mgis_1_1_material_quantity_provider_search_result" ],
      [ "MeanThermodynamicForces", "structmfem__mgis_1_1_mean_thermodynamic_forces.html", "structmfem__mgis_1_1_mean_thermodynamic_forces" ],
      [ "MeshDiscretization", "structmfem__mgis_1_1_mesh_discretization.html", "structmfem__mgis_1_1_mesh_discretization" ],
      [ "ModelBase", "structmfem__mgis_1_1_model_base.html", "structmfem__mgis_1_1_model_base" ],
      [ "MultiMaterialNonLinearIntegrator", "structmfem__mgis_1_1_multi_material_non_linear_integrator.html", "structmfem__mgis_1_1_multi_material_non_linear_integrator" ],
      [ "MultipleCurves", "structmfem__mgis_1_1_multiple_curves.html", "structmfem__mgis_1_1_multiple_curves" ],
      [ "NewtonSolver", "structmfem__mgis_1_1_newton_solver.html", "structmfem__mgis_1_1_newton_solver" ],
      [ "NonLinearEvolutionProblem", "structmfem__mgis_1_1_non_linear_evolution_problem.html", "structmfem__mgis_1_1_non_linear_evolution_problem" ],
      [ "NonLinearEvolutionProblemImplementation", "structmfem__mgis_1_1_non_linear_evolution_problem_implementation.html", null ],
      [ "NonLinearEvolutionProblemImplementation< false >", "structmfem__mgis_1_1_non_linear_evolution_problem_implementation_3_01false_01_4.html", "structmfem__mgis_1_1_non_linear_evolution_problem_implementation_3_01false_01_4" ],
      [ "NonLinearEvolutionProblemImplementation< true >", "structmfem__mgis_1_1_non_linear_evolution_problem_implementation_3_01true_01_4.html", "structmfem__mgis_1_1_non_linear_evolution_problem_implementation_3_01true_01_4" ],
      [ "NonLinearEvolutionProblemImplementationBase", "structmfem__mgis_1_1_non_linear_evolution_problem_implementation_base.html", "structmfem__mgis_1_1_non_linear_evolution_problem_implementation_base" ],
      [ "NonLinearModel", "structmfem__mgis_1_1_non_linear_model.html", "structmfem__mgis_1_1_non_linear_model" ],
      [ "NonLinearResolutionOutput", "structmfem__mgis_1_1_non_linear_resolution_output.html", "structmfem__mgis_1_1_non_linear_resolution_output" ],
      [ "NonLinearSolverBase", "structmfem__mgis_1_1_non_linear_solver_base.html", "structmfem__mgis_1_1_non_linear_solver_base" ],
      [ "NonLinearSolverFactory", "structmfem__mgis_1_1_non_linear_solver_factory.html", "structmfem__mgis_1_1_non_linear_solver_factory" ],
      [ "OrthotropicBidimensionalMicromorphicDamageBehaviourIntegrator", "structmfem__mgis_1_1_orthotropic_bidimensional_micromorphic_damage_behaviour_integrator.html", "structmfem__mgis_1_1_orthotropic_bidimensional_micromorphic_damage_behaviour_integrator" ],
      [ "OrthotropicPlaneStrainStandardFiniteStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_orthotropic_plane_strain_standard_finite_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_orthotropic_plane_strain_standard_finite_strain_mechanics_behaviour_integrator" ],
      [ "OrthotropicPlaneStrainStandardSmallStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_orthotropic_plane_strain_standard_small_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_orthotropic_plane_strain_standard_small_strain_mechanics_behaviour_integrator" ],
      [ "OrthotropicPlaneStrainStationaryNonLinearHeatTransferBehaviourIntegrator", "structmfem__mgis_1_1_orthotropic_plane_strain_stationary_non_linear_heat_transfer_behaviour_integrator.html", "structmfem__mgis_1_1_orthotropic_plane_strain_stationary_non_linear_heat_transfer_behaviour_integrator" ],
      [ "OrthotropicPlaneStressStandardFiniteStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_orthotropic_plane_stress_standard_finite_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_orthotropic_plane_stress_standard_finite_strain_mechanics_behaviour_integrator" ],
      [ "OrthotropicPlaneStressStandardSmallStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_orthotropic_plane_stress_standard_small_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_orthotropic_plane_stress_standard_small_strain_mechanics_behaviour_integrator" ],
      [ "OrthotropicPlaneStressStationaryNonLinearHeatTransferBehaviourIntegrator", "structmfem__mgis_1_1_orthotropic_plane_stress_stationary_non_linear_heat_transfer_behaviour_integrator.html", "structmfem__mgis_1_1_orthotropic_plane_stress_stationary_non_linear_heat_transfer_behaviour_integrator" ],
      [ "OrthotropicTridimensionalStandardFiniteStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_orthotropic_tridimensional_standard_finite_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_orthotropic_tridimensional_standard_finite_strain_mechanics_behaviour_integrator" ],
      [ "OrthotropicTridimensionalStandardSmallStrainMechanicsBehaviourIntegrator", "structmfem__mgis_1_1_orthotropic_tridimensional_standard_small_strain_mechanics_behaviour_integrator.html", "structmfem__mgis_1_1_orthotropic_tridimensional_standard_small_strain_mechanics_behaviour_integrator" ],
      [ "OrthotropicTridimensionalStationaryNonLinearHeatTransferBehaviourIntegrator", "structmfem__mgis_1_1_orthotropic_tridimensional_stationary_non_linear_heat_transfer_behaviour_integrator.html", "structmfem__mgis_1_1_orthotropic_tridimensional_stationary_non_linear_heat_transfer_behaviour_integrator" ],
      [ "Parameter", "structmfem__mgis_1_1_parameter.html", "structmfem__mgis_1_1_parameter" ],
      [ "Parameters", "structmfem__mgis_1_1_parameters.html", "structmfem__mgis_1_1_parameters" ],
      [ "ParametersValidator", "structmfem__mgis_1_1_parameters_validator.html", "structmfem__mgis_1_1_parameters_validator" ],
      [ "ParaviewExportIntegrationPointResultsAtNodes", "structmfem__mgis_1_1_paraview_export_integration_point_results_at_nodes.html", "structmfem__mgis_1_1_paraview_export_integration_point_results_at_nodes" ],
      [ "ParaviewExportIntegrationPointResultsAtNodesBase", "structmfem__mgis_1_1_paraview_export_integration_point_results_at_nodes_base.html", "structmfem__mgis_1_1_paraview_export_integration_point_results_at_nodes_base" ],
      [ "ParaviewExportIntegrationPointResultsAtNodesImplementation", "structmfem__mgis_1_1_paraview_export_integration_point_results_at_nodes_implementation.html", "structmfem__mgis_1_1_paraview_export_integration_point_results_at_nodes_implementation" ],
      [ "ParaviewExportResults", "structmfem__mgis_1_1_paraview_export_results.html", "structmfem__mgis_1_1_paraview_export_results" ],
      [ "PartialQuadratureFunction", "structmfem__mgis_1_1_partial_quadrature_function.html", "structmfem__mgis_1_1_partial_quadrature_function" ],
      [ "PartialQuadratureFunctionDataLayout", "structmfem__mgis_1_1_partial_quadrature_function_data_layout.html", "structmfem__mgis_1_1_partial_quadrature_function_data_layout" ],
      [ "PartialQuadratureFunctionsSet", "structmfem__mgis_1_1_partial_quadrature_functions_set.html", "structmfem__mgis_1_1_partial_quadrature_functions_set" ],
      [ "PartialQuadratureFunctionView", "structmfem__mgis_1_1_partial_quadrature_function_view.html", "structmfem__mgis_1_1_partial_quadrature_function_view" ],
      [ "PartialQuadratureSpace", "structmfem__mgis_1_1_partial_quadrature_space.html", "structmfem__mgis_1_1_partial_quadrature_space" ],
      [ "PartialQuadratureSpaceIdentifiersManager", "structmfem__mgis_1_1_partial_quadrature_space_identifiers_manager.html", "structmfem__mgis_1_1_partial_quadrature_space_identifiers_manager" ],
      [ "PeriodicNonLinearEvolutionProblem", "structmfem__mgis_1_1_periodic_non_linear_evolution_problem.html", "structmfem__mgis_1_1_periodic_non_linear_evolution_problem" ],
      [ "PhysicalSystem", "structmfem__mgis_1_1_physical_system.html", "structmfem__mgis_1_1_physical_system" ],
      [ "PlaneStrainStandardFiniteStrainMechanicsBehaviourIntegratorBase", "structmfem__mgis_1_1_plane_strain_standard_finite_strain_mechanics_behaviour_integrator_base.html", "structmfem__mgis_1_1_plane_strain_standard_finite_strain_mechanics_behaviour_integrator_base" ],
      [ "PlaneStressStandardFiniteStrainMechanicsBehaviourIntegratorBase", "structmfem__mgis_1_1_plane_stress_standard_finite_strain_mechanics_behaviour_integrator_base.html", "structmfem__mgis_1_1_plane_stress_standard_finite_strain_mechanics_behaviour_integrator_base" ],
      [ "PointsSetCurves", "structmfem__mgis_1_1_points_set_curves.html", "structmfem__mgis_1_1_points_set_curves" ],
      [ "PointsSetCurvesPostProcessing", "structmfem__mgis_1_1_points_set_curves_post_processing.html", "structmfem__mgis_1_1_points_set_curves_post_processing" ],
      [ "PointsSetCurvesWriter", "structmfem__mgis_1_1_points_set_curves_writer.html", "structmfem__mgis_1_1_points_set_curves_writer" ],
      [ "PointWiseModel", "structmfem__mgis_1_1_point_wise_model.html", "structmfem__mgis_1_1_point_wise_model" ],
      [ "PostProcessingBase", "structmfem__mgis_1_1_post_processing_base.html", "structmfem__mgis_1_1_post_processing_base" ],
      [ "PostProcessingFactory", "structmfem__mgis_1_1_post_processing_factory.html", null ],
      [ "PostProcessingFactory< false >", "structmfem__mgis_1_1_post_processing_factory_3_01false_01_4.html", "structmfem__mgis_1_1_post_processing_factory_3_01false_01_4" ],
      [ "PostProcessingFactory< true >", "structmfem__mgis_1_1_post_processing_factory_3_01true_01_4.html", "structmfem__mgis_1_1_post_processing_factory_3_01true_01_4" ],
      [ "PredictionPolicy", "structmfem__mgis_1_1_prediction_policy.html", "structmfem__mgis_1_1_prediction_policy" ],
      [ "Provider", "structmfem__mgis_1_1_provider.html", "structmfem__mgis_1_1_provider" ],
      [ "QPDependency", "structmfem__mgis_1_1_q_p_dependency.html", "structmfem__mgis_1_1_q_p_dependency" ],
      [ "QPEvaluationOptions", "structmfem__mgis_1_1_q_p_evaluation_options.html", null ],
      [ "QPEvaluatorBase", "structmfem__mgis_1_1_q_p_evaluator_base.html", "structmfem__mgis_1_1_q_p_evaluator_base" ],
      [ "QPEvaluatorDescription", "structmfem__mgis_1_1_q_p_evaluator_description.html", "structmfem__mgis_1_1_q_p_evaluator_description" ],
      [ "QPEvaluatorResult", "structmfem__mgis_1_1_q_p_evaluator_result.html", "structmfem__mgis_1_1_q_p_evaluator_result" ],
      [ "QPEvaluatorsFactory", "structmfem__mgis_1_1_q_p_evaluators_factory.html", "structmfem__mgis_1_1_q_p_evaluators_factory" ],
      [ "RotatedGradientsMatrixQPEvaluator", "structmfem__mgis_1_1_rotated_gradients_matrix_q_p_evaluator.html", "structmfem__mgis_1_1_rotated_gradients_matrix_q_p_evaluator" ],
      [ "RotatedThermodynamicForcesMatrixQPEvaluator", "structmfem__mgis_1_1_rotated_thermodynamic_forces_matrix_q_p_evaluator.html", "structmfem__mgis_1_1_rotated_thermodynamic_forces_matrix_q_p_evaluator" ],
      [ "RotationMatrixQPEvaluator", "structmfem__mgis_1_1_rotation_matrix_q_p_evaluator.html", "structmfem__mgis_1_1_rotation_matrix_q_p_evaluator" ],
      [ "Simulation", "structmfem__mgis_1_1_simulation.html", "structmfem__mgis_1_1_simulation" ],
      [ "SimulationOutput", "structmfem__mgis_1_1_simulation_output.html", "structmfem__mgis_1_1_simulation_output" ],
      [ "StandardBehaviourIntegratorCRTPBase", "structmfem__mgis_1_1_standard_behaviour_integrator_c_r_t_p_base.html", "structmfem__mgis_1_1_standard_behaviour_integrator_c_r_t_p_base" ],
      [ "StandardNonLinearSolverGenerator", "structmfem__mgis_1_1_standard_non_linear_solver_generator.html", "structmfem__mgis_1_1_standard_non_linear_solver_generator" ],
      [ "StandardQPEvaluator", "structmfem__mgis_1_1_standard_q_p_evaluator.html", "structmfem__mgis_1_1_standard_q_p_evaluator" ],
      [ "StateManager", "structmfem__mgis_1_1_state_manager.html", "structmfem__mgis_1_1_state_manager" ],
      [ "StoredEnergyPostProcessing", "structmfem__mgis_1_1_stored_energy_post_processing.html", "structmfem__mgis_1_1_stored_energy_post_processing" ],
      [ "TimeIncrementComputerBase", "structmfem__mgis_1_1_time_increment_computer_base.html", "structmfem__mgis_1_1_time_increment_computer_base" ],
      [ "TimeStep", "structmfem__mgis_1_1_time_step.html", "structmfem__mgis_1_1_time_step" ],
      [ "TimeStepValidatorBase", "structmfem__mgis_1_1_time_step_validator_base.html", "structmfem__mgis_1_1_time_step_validator_base" ],
      [ "TransientHeatTransferBehaviourIntegrator", "structmfem__mgis_1_1_transient_heat_transfer_behaviour_integrator.html", "structmfem__mgis_1_1_transient_heat_transfer_behaviour_integrator" ],
      [ "TridimensionalMicromorphicDamageBehaviourIntegrator", "structmfem__mgis_1_1_tridimensional_micromorphic_damage_behaviour_integrator.html", "structmfem__mgis_1_1_tridimensional_micromorphic_damage_behaviour_integrator" ],
      [ "TridimensionalStandardFiniteStrainMechanicsBehaviourIntegratorBase", "structmfem__mgis_1_1_tridimensional_standard_finite_strain_mechanics_behaviour_integrator_base.html", "structmfem__mgis_1_1_tridimensional_standard_finite_strain_mechanics_behaviour_integrator_base" ],
      [ "UniformConstantScalarQPEvaluator", "structmfem__mgis_1_1_uniform_constant_scalar_q_p_evaluator.html", "structmfem__mgis_1_1_uniform_constant_scalar_q_p_evaluator" ],
      [ "UniformDirichletBoundaryCondition", "structmfem__mgis_1_1_uniform_dirichlet_boundary_condition.html", "structmfem__mgis_1_1_uniform_dirichlet_boundary_condition" ],
      [ "UniformHeatSourceBoundaryCondition", "structmfem__mgis_1_1_uniform_heat_source_boundary_condition.html", "structmfem__mgis_1_1_uniform_heat_source_boundary_condition" ],
      [ "UniformImposedPressureBoundaryCondition", "structmfem__mgis_1_1_uniform_imposed_pressure_boundary_condition.html", "structmfem__mgis_1_1_uniform_imposed_pressure_boundary_condition" ],
      [ "UniformScalarQPEvaluator", "structmfem__mgis_1_1_uniform_scalar_q_p_evaluator.html", "structmfem__mgis_1_1_uniform_scalar_q_p_evaluator" ],
      [ "UniformScalarQPEvaluatorBase", "structmfem__mgis_1_1_uniform_scalar_q_p_evaluator_base.html", "structmfem__mgis_1_1_uniform_scalar_q_p_evaluator_base" ],
      [ "ViewSpecifications", "structmfem__mgis_1_1_view_specifications.html", "structmfem__mgis_1_1_view_specifications" ]
    ] ],
    [ "mgis", null, [
      [ "internal", null, [
        [ "InvalidValueTraits< mfem_mgis::ExitStatus >", "structmgis_1_1internal_1_1_invalid_value_traits_3_01mfem__mgis_1_1_exit_status_01_4.html", null ],
        [ "InvalidValueTraits< mfem_mgis::LinearSolverHandler >", "structmgis_1_1internal_1_1_invalid_value_traits_3_01mfem__mgis_1_1_linear_solver_handler_01_4.html", null ],
        [ "InvalidValueTraits< mfem_mgis::NonLinearResolutionOutput >", "structmgis_1_1internal_1_1_invalid_value_traits_3_01mfem__mgis_1_1_non_linear_resolution_output_01_4.html", null ],
        [ "InvalidValueTraits<::mfem_mgis::LocationIdentifier >", "structmgis_1_1internal_1_1_invalid_value_traits_3_1_1mfem__mgis_1_1_location_identifier_01_4.html", null ]
      ] ]
    ] ]
];